config/routes.rb
Rails.application.routes.draw do
  resources :cuisines

  get 'pages/home'

  get 'pages/results'

  post 'pages/results'
  get 'pages/top_restaurants'

  resources :review_counts

  resources :reviews

  resources :locations

  resources :restaurants

end

app/models/review_count.rb
class ReviewCount < ActiveRecord::Base
end

app/controllers/review_counts_controller.rb
class ReviewCountsController < ApplicationController
  before_action :set_review_count, only: [:show, :edit, :update, :destroy]

  # GET /review_counts
  # GET /review_counts.json
  def index
    @review_counts = ReviewCount.all
  end

  # GET /review_counts/1
  # GET /review_counts/1.json
  def show
  end

  # GET /review_counts/new
  def new
    @review_count = ReviewCount.new
  end

  # GET /review_counts/1/edit
  def edit
  end

  # POST /review_counts
  # POST /review_counts.json
  def create
    @review_count = ReviewCount.new(review_count_params)

    respond_to do |format|
      if @review_count.save
        format.html { redirect_to @review_count, notice: 'Review count was successfully created.' }
        format.json { render :show, status: :created, location: @review_count }
      else
        format.html { render :new }
        format.json { render json: @review_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /review_counts/1
  # PATCH/PUT /review_counts/1.json
  def update
    respond_to do |format|
      if @review_count.update(review_count_params)
        format.html { redirect_to @review_count, notice: 'Review count was successfully updated.' }
        format.json { render :show, status: :ok, location: @review_count }
      else
        format.html { render :edit }
        format.json { render json: @review_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /review_counts/1
  # DELETE /review_counts/1.json
  def destroy
    @review_count.destroy
    respond_to do |format|
      format.html { redirect_to review_counts_url, notice: 'Review count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_count
      @review_count = ReviewCount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_count_params
      params.require(:review_count).permit(:rest_id, :rev_count)
    end
end

app/helpers/review_counts_helper.rb
module ReviewCountsHelper
end

app/views/review_counts/_form.html.erb
<%= simple_form_for @review_count, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :rest_id %>
  <%= error_span(@review_count[:rest_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                review_counts_path, :class => 'btn btn-default' %>
<% end %>

app/views/review_counts/edit.html.erb
<%- model_class = ReviewCount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/review_counts/index.html.erb
<%- model_class = ReviewCount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rest_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @review_counts.each do |review_count| %>
      <tr>
        <td><%= link_to review_count.id, review_count_path(review_count) %></td>
        <td><%= review_count.rest_id %></td>
        <td><%=l review_count.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_review_count_path(review_count), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      review_count_path(review_count),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_review_count_path,
            :class => 'btn btn-primary' %>

app/views/review_counts/new.html.erb
<%- model_class = ReviewCount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/review_counts/show.html.erb
<%- model_class = ReviewCount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rest_id) %>:</strong></dt>
  <dd><%= @review_count.rest_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              review_counts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_count_path(@review_count), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_count_path(@review_count),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>