config/routes.rb
Rails.application.routes.draw do
  resources :cuisines

  get 'pages/home'

  get 'pages/results'

  post 'pages/results'
  get 'pages/top_restaurants'

  resources :review_counts

  resources :reviews

  resources :locations

  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:rest_id, :name, :location, :loc_id, :zone_name, :zone_id, :city_name, :city_id, :cuisines, :twitter_handle, :cost_for_two, :rating)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :rest_id %>
  <%= error_span(@restaurant[:rest_id]) %>
  <%= f.input :name %>
  <%= error_span(@restaurant[:name]) %>
  <%= f.input :location %>
  <%= error_span(@restaurant[:location]) %>
  <%= f.input :loc_id %>
  <%= error_span(@restaurant[:loc_id]) %>
  <%= f.input :zone_name %>
  <%= error_span(@restaurant[:zone_name]) %>
  <%= f.input :zone_id %>
  <%= error_span(@restaurant[:zone_id]) %>
  <%= f.input :city_name %>
  <%= error_span(@restaurant[:city_name]) %>
  <%= f.input :city_id %>
  <%= error_span(@restaurant[:city_id]) %>
  <%= f.input :cuisines %>
  <%= error_span(@restaurant[:cuisines]) %>
  <%= f.input :twitter_handle %>
  <%= error_span(@restaurant[:twitter_handle]) %>
  <%= f.input :cost_for_two %>
  <%= error_span(@restaurant[:cost_for_two]) %>
  <%= f.input :rating %>
  <%= error_span(@restaurant[:rating]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurants_path, :class => 'btn btn-default' %>
<% end %>

app/views/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rest_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:loc_id) %></th>
      <th><%= model_class.human_attribute_name(:zone_name) %></th>
      <th><%= model_class.human_attribute_name(:zone_id) %></th>
      <th><%= model_class.human_attribute_name(:city_name) %></th>
      <th><%= model_class.human_attribute_name(:city_id) %></th>
      <th><%= model_class.human_attribute_name(:cuisines) %></th>
      <th><%= model_class.human_attribute_name(:twitter_handle) %></th>
      <th><%= model_class.human_attribute_name(:cost_for_two) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.id, restaurant_path(restaurant) %></td>
        <td><%= restaurant.rest_id %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.loc_id %></td>
        <td><%= restaurant.zone_name %></td>
        <td><%= restaurant.zone_id %></td>
        <td><%= restaurant.city_name %></td>
        <td><%= restaurant.city_id %></td>
        <td><%= restaurant.cuisines %></td>
        <td><%= restaurant.twitter_handle %></td>
        <td><%= restaurant.cost_for_two %></td>
        <td><%= restaurant.rating %></td>
        <td><%=l restaurant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurant_path(restaurant), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurant_path(restaurant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurant_path,
            :class => 'btn btn-primary' %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rest_id) %>:</strong></dt>
  <dd><%= @restaurant.rest_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @restaurant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @restaurant.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:loc_id) %>:</strong></dt>
  <dd><%= @restaurant.loc_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zone_name) %>:</strong></dt>
  <dd><%= @restaurant.zone_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zone_id) %>:</strong></dt>
  <dd><%= @restaurant.zone_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city_name) %>:</strong></dt>
  <dd><%= @restaurant.city_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city_id) %>:</strong></dt>
  <dd><%= @restaurant.city_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cuisines) %>:</strong></dt>
  <dd><%= @restaurant.cuisines %></dd>
  <dt><strong><%= model_class.human_attribute_name(:twitter_handle) %>:</strong></dt>
  <dd><%= @restaurant.twitter_handle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cost_for_two) %>:</strong></dt>
  <dd><%= @restaurant.cost_for_two %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @restaurant.rating %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              restaurants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_restaurant_path(@restaurant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              restaurant_path(@restaurant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>